"""Initial migration2

Revision ID: 2f3a71c4af25
Revises: 89c9f39c344a
Create Date: 2024-12-22 21:59:49.647311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3a71c4af25'
down_revision: Union[str, None] = '89c9f39c344a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('disease', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ML_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('model', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('doctor_specialty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Patient')
    op.drop_table('ML_user')
    op.drop_table('Doctor')
    op.drop_table('User')
    # ### end Alembic commands ###
