"""Add target, accuracy column to ML model

Revision ID: ad3e521fdb0d
Revises: fcfec50a2c9e
Create Date: 2025-05-10 20:52:10.846753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3e521fdb0d'
down_revision: Union[str, None] = 'fcfec50a2c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ML_user', sa.Column('accuracy', sa.String(), nullable=True))
    op.add_column('ML_user', sa.Column('target', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ML_user', 'target')
    op.drop_column('ML_user', 'accuracy')
    # ### end Alembic commands ###
